code: default
name:
  default_value: Certificate
  key: default.name

description:
  default_value: Certificate Launch
  key: default.description

messages:
  - type: basic-lti-launch-request
    route:
      path: "/default"
      controller: "certificates"
      action: "index"
### List of parameters ###
# parameters:
#   - name: context_type #the name of the parameter
#     #fixed: #a fixed value you want to substitute in
#   - name: #the name of the parameter
#     variable: #the variable substitution that you want to get
#     required: #set to true if you want registration to fail if not the variable is not available
### List of required capabilities ###
#    required_capabilities:
#      - #name of a required capability
### List of optional capabilities ###
#    optional_capabilities:
#      - #name of a optional capability